name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Docker Login
      uses: docker/login-action@v2
      with:
        registry: registry.antosubash.com
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    - uses: actions/checkout@v2
    - name: Build the abptemplate Docker image
      run: docker build . --file abp/AbpTemplate/Dockerfile --tag abptemplate:dev
    - name: Docker tag images
      run: docker tag abptemplate:dev registry.antosubash.com/abptemplate:dev
    - name: Push abptemplate image
      run: docker push registry.antosubash.com/abptemplate:dev
    - name: Send Http Post Request to Deploy API
      uses: fjogeleit/http-request-action@v1
      with:
        url: ${{ secrets.WEBHOOK_URL }}
        method: 'POST'